[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "freeworld"
version = "0.1.0"
description = "Example project structure"

[tool.pytest.ini_options]
addopts = "-ra"
